name: 'jfr-runtime-action'
description: 'Run the Jenkins pipeline with Jenkinsfile-runner'
inputs:
  command:
    description: Jenkinsfile-runner command, i.e; run or lint
    default: run
    required: false
  jenkinsfile:
    description: Jenkinsfile location to test
    default: Jenkinsfile
    required: true
  jcasc:
    description: Jenkins CasC file
    required: false
  initHook:
    description: Path to the Groovy init hook directory
    required: false
runs:
  using: "composite"
  steps:
    - name: Run Jenkins pipeline
      env:
        CASC_JENKINS_CONFIG: jenkins/casc
      run: ${GITHUB_ACTION_PATH}/setup.sh ${{inputs.command}} ${{inputs.jenkinsfile}} ${{inputs.jcasc}} ${{inputs.initHook}}
      shell: bash
